spring:
  cloud:
    nacos:
      discovery:
        namespace: prod
      config:
        namespace: prod
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
