spring:
  cloud:
    nacos:
      discovery:
        enabled: false
        register-enabled: false
      config:
        enabled: false
        import-check:
          enabled: false
  datasource:
    url: jdbc:{{DB_DIALECT_KEY}}://localhost:5432/{{DB_NAME}}_test
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: { { DB_DRIVER } }
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
